apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "btserver.fullname" . }}
  labels:
    {{- include "btserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "btserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "btserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      serviceAccountName: {{ include "btserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.containers.network }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containers.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containers.port }}
          volumeMounts:
          - name: {{ .Values.volumeMounts.name }}
            mountPath: {{ .Values.volumeMounts.path }}
          resources: {}
        - name: {{ .Values.containers.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository_track }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containers.port_track }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containers.port_track }}
          volumeMounts:
          - name: {{ .Values.volumeMounts.name_track }}
            mountPath: {{ .Values.volumeMounts.path_track }}
          resources: {}
      volumes:
      - name: {{ .Values.volumes.name }}
        hostPath:
          path: {{ .Values.volumes.path }}
          type: {{ .Values.volumes.type }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
