---
- name: get ssd disk capacity
  shell: "lsblk | grep {{ ssd_disk }} | awk '{print $4}'"
  register: DiskResult
  when:
    - rbd_parent_cache_enabled | bool

- name: set_fact
  set_fact:
    ssd_disk_capacity: "{{ DiskResult.stdout }}"

- name: cephfile-conf
  template:
    src: ceph.conf.j2
    dest: /var/lib/ceph/tmp/ceph.conf
  register: ceph_conf

- name: set_fact
  set_fact:
    cephf_conf: ceph_conf

- name: Copy file with owner and permissions
  copy:
    src: /var/lib/ceph/tmp/ceph.conf
    dest: /etc/ceph/ceph.conf
    remote_src: "yes"
  when:
    - ceph_conf.changed
