- name: 读取 kubelet.conf 文件 stat 信息
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- name: 拉取 worker 节点需要拉取的镜像列表
  shell: kubeadm config images pull --image-repository={{ kube_image_repository }} --kubernetes-version={{ kubernetes_version }}

- name: Worker 节点加入集群
  shell: kubeadm join {{ apiServerEndpoint }}:{{ kube_apiserver_port }} --token {{ kubeadm_token }} --discovery-token-unsafe-skip-ca-verification --node-name {{ inventory_hostname }}
  when: 
  - inventory_hostname in (groups['kube-worker'] + groups['new-worker'])
  - inventory_hostname not in (groups['kube-master'] + groups['new-master'])
  - not kubelet_conf_stat.stat.exists

- name: 查看 k8s 节点 compute标签
  shell: kubectl get nodes --show-labels | grep {{ inventory_hostname }} | grep {{ compute_node_role_name }} | wc -l
  register: node_compute_role

- name: 查看 k8s 节点 storage标签
  shell: kubectl get nodes --show-labels | grep {{ inventory_hostname }} | grep {{ storage_node_role_name }} | wc -l
  register: node_storage_role

- name: group not have compute labels node
  group_by:
    key: "all_using_limit_compute_{{ node_compute_role.stdout == '0' }}"

- name: 设置 compute node lables
  shell: kubectl label node {{ inventory_hostname }} {{ compute_node_role_name }}={{ node_role_value }}
  when: inventory_hostname in groups['all_using_limit_compute_True']
  ignore_errors: yes

- name: group not have storage labels node
  group_by:
    key: "all_using_limit_storage_{{ node_storage_role.stdout == '0' }}"

- name: 设置 storage node lables
  shell: kubectl label node {{ inventory_hostname }} {{ storage_node_role_name }}={{ node_role_value }}
  when: inventory_hostname in groups['all_using_limit_storage_True']
  ignore_errors: yes
