apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsd
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      type: fsd
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: fsd
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: {{ .Values.tolerationSeconds }}
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: {{ .Values.tolerationSeconds }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                    - fsd
              topologyKey: 'kubernetes.io/hostname'
      containers:
        - name: fsd
          image: {{ .Values.image.fsd }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.fsd_webhook.port }}
              protocol: TCP
              name: {{ .Values.service.fsd_webhook.name }}
            - containerPort: {{ .Values.service.fsd_tcp.port }}
              protocol: TCP
              name: {{ .Values.service.fsd_tcp.name }}
            - containerPort: {{ .Values.service.fsd_tcp_file.port }}
              protocol: TCP
              name: {{ .Values.service.fsd_tcp_file.name }}
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - name: fsd-log
              mountPath: /log
            - name: fsd-prometheus-rule
              mountPath: /home/static/prometheus/rules
            - name: fsd-prometheus-alert
              mountPath: /home/static/prometheus/alert/alertmanager.yml
            - name: fsd-voi
              mountPath: "{{ .Values.containerPath.voi }}"
            - name: fsd-upload
              mountPath: "{{ .Values.containerPath.upload }}"
            - name: fsd-static
              mountPath: "{{ .Values.containerPath.fsd_static }}"
            - name: samba-dir
              mountPath: "{{ .Values.fsd_env.cloud_disk_root_path }}"
          env:
            - name: ENV_FSD_SPRING_MYSQL_PASSWORD
              value: "{{ .Values.fsd_job_env.mariadb_password }}"
            - name: ENV_FSD_SPRING_REDIS_PASSWORD
              value: "{{ .Values.fsd_env.redis_password }}"
            - name: ENV_FSD_BIZ_DEPLOY_SVC_REDIS
              value: "{{ .Values.fsd_env.redis_server_address }}"
            - name: SPRING_REDIS_SENTINEL_MASTER
              value: "{{ .Values.fsd_env.redis_master_name }}"
            - name: SPRING_REDIS_SENTINEL_NODES
              value: "{{ printf %s:%s .Values.fsd_env.redis_server_address .Values.fsd_env.redis_sentinel_port }}"
            - name: ENV_FSD_BIZ_DEPLOY_SVC_MYSQL
              value: "{{ .Values.fsd_env.mariadb_server_address }}"
            - name: ENV_FSD_BIZ_DEPLOY_SVC_EMQX
              value: "{{ .Values.fsd_env.emqx_server_address }}"
            - name: ENV_FSD_BIZ_DEPLOY_SVC_THANOS
              value: "{{ .Values.fsd_env.thanos_server_address }}"
            - name: ENV_FSD_BIZ_DEPLOY_SVC_JOB
              value: "{{ .Values.fsd_env.fsd_job_server_address }}"
            - name: ENV_FSD_BIZ_DEPLOY_SVC_VIRTUALAPI
              value: "{{ .Values.fsd_env.trochilus_server_address }}"
            - name: ENV_FSD_BIZ_DEPLOY_SVC_BTSERVER
              value: "{{ .Values.fsd_env.btserver_server_address }}"
            - name: ENV_FSD_COMMON_NETTY_CODEC_MAC
              value: "{{ .Values.fsd_env.netty_codec_mac }}"
            - name: ENV_FSD_BIZ_DEPLOY_MODE
              value: "{{ .Values.fsd_env.deploy_mode }}"
            - name: ENV_FSD_BIZ_DEPLOY_PROXYIP
              value: "{{ .Values.fsd_env.proxy_ip }}"
            - name: ENV_FSD_BIZ_DEPLOY_VIP
              value: "{{ .Values.fsd_env.deploy_vip }}"
            - name: ENV_FSD_BIZ_VIRTUAL_VNCPORT
              value: "{{ .Values.fsd_env.vnc_port }}"
            - name: ENV_FSD_BIZ_DEPLOY_NODEIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: ENV_FSD_BIZ_DESKTOP_BT_PORTSTART
              value: "{{ .Values.fsd_env.desktop_bt_port_start }}"
            - name: ENV_FSD_BIZ_DESKTOP_BT_PORTEND
              value: "{{ .Values.fsd_env.desktop_bt_port_end }}"
            - name: ENV_FSD_BIZ_PATH_SHAREROOTPATH
              value: "{{ .Values.fsd_env.share_root_path }}"
            - name: ENV_FSD_BIZ_CLOUDDISK_ROOTPATH
              value: "{{ .Values.fsd_env.cloud_disk_root_path }}"
            - name: ENV_FSD_BIZ_CLOUDDISK_SHAREDDISKMAPPATH
              value: "{{ .Values.fsd_env.cloud_disk_share_disk_path }}"
            - name: ENV_FSD_BIZ_CLOUDDISK_CLOUDDISKUSERNAME
              value: "{{ .Values.fsd_env.cloud_disk_username }}"
            - name: ENV_FSD_BIZ_CLOUDDISK_CLOUDDISKPASSWORD
              value: "{{ .Values.fsd_env.cloud_disk_password }}"
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: fsd-log
          hostPath:
            path: "{{ .Values.mount_dir.fsd_log }}"
            type: DirectoryOrCreate
        - name: fsd-prometheus-rule
          hostPath:
            path: "{{ .Values.mount_dir.prometheus_rule }}"
            type: DirectoryOrCreate
        - name: fsd-prometheus-alert
          hostPath:
            path: "{{ .Values.mount_dir.alertmanager_conf }}"
            type: FileOrCreate
        - name: fsd-voi
          hostPath:
            path: "{{ .Values.mount_dir.voi_dir }}"
            type: DirectoryOrCreate
        - name: fsd-upload
          hostPath:
            path: "{{ .Values.mount_dir.upload_dir }}"
            type: DirectoryOrCreate
        - name: fsd-static
          hostPath:
            path: "{{ .Values.mount_dir.fsd_static }}"
            type: DirectoryOrCreate
        - name: samba-dir
          hostPath:
            path: "{{ .Values.mount_dir.samba_dir }}"
            type: DirectoryOrCreate
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      serviceAccount: {{ .Values.serviceAccountName }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
